import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class"],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        "bg-sidebar": "var(--color-bg-sidebar)",
        "bg-raised": "var(--color-bg-raised)",
        "bg-sunken": "var(--color-bg-sunken)",
        "bg-hover": "var(--color-bg-hover)",
        "bg-overlay": "var(--color-bg-overlay)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "border-accent": "var(--color-border-accent)",
        fg: "var(--color-fg)",
        "fg-muted": "var(--color-fg-muted)",
        "fg-subtle": "var(--color-fg-subtle)",
        "fg-inverse": "var(--color-fg-inverse)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-fg": "var(--color-accent-fg)",
        "accent-wash": "var(--color-accent-wash)",
        "accent-glow": "var(--color-accent-glow)",
        danger: "var(--color-danger)",
        "danger-wash": "var(--color-danger-wash)",
        success: "var(--color-success)",
        "success-wash": "var(--color-success-wash)",
        warning: "var(--color-warning)",
        "warning-wash": "var(--color-warning-wash)",
        info: "var(--color-info)",
        "info-wash": "var(--color-info-wash)",
      },
      fontFamily: {
        mono: [
          "'JetBrains Mono'",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
        sans: [
          "'Instrument Sans'",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "Roboto",
          "'Helvetica Neue'",
          "Arial",
          "sans-serif",
        ],
        serif: [
          "'Newsreader'",
          "Georgia",
          "serif",
        ],
      },
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
      },
      borderRadius: {
        DEFAULT: "var(--radius-md)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        popover: "var(--shadow-popover)",
      },
    },
  },
  plugins: [],
} satisfies Config;
